package Components.Events.project;

import ClaseFisiere.project.FisierSingle;

import ClaseFisiere.project.FisierSingleDAO;

import DataBaseConn.project.DataBaseConn;

import Digitalizare.Laborator.Metrologie.project.DLMAppStart;

import Users.project.Users;

import java.awt.Color;
import java.awt.Font;

import java.io.File;

import java.io.IOException;

import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;

import java.nio.file.Paths;

import java.nio.file.StandardCopyOption;

import java.sql.SQLException;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dragos
 */
public class MeniuAdmFisiere extends javax.swing.JPanel {
    String connectionUrl = String.format("jdbc:mysql://%s:%s/%s", "127.0.0.1", "3306", "dsr");
    DataBaseConn db = new DataBaseConn(connectionUrl, "root", "@Root123#");
    
    FisierSingleDAO fisierSingleManagement = new FisierSingleDAO(db.getConnection());
    
    List<FisierSingle> fisiereSingle = new ArrayList<>();
    
    String fisiereApp = "C:\\Oracle\\Middleware\\Oracle_Home\\jdeveloper\\mywork\\" +
                        "mywork\\DigitalizareLaboratorMetrologie\\project\\FisiereDLM\\";
    /** Creates new form MeniuAdmFisiere */
    public MeniuAdmFisiere() {
        try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLMAppStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.updateUI();
        selectoareMapeSiFisiere();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jTabbedPaneAdmFisiere = new javax.swing.JTabbedPane();
        jPanelMeniuFisiere = new javax.swing.JPanel();
        jLabelTitluAdmFisiere = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFisiere = new javax.swing.JTable();
        jBtnVizFisiere = new javax.swing.JButton();
        jPanelAdaugaFisiere = new javax.swing.JPanel();
        jLabelTitluAdaugareFisiere = new javax.swing.JLabel();
        jLabelNumeFisier = new javax.swing.JLabel();
        jLabelTipFisier = new javax.swing.JLabel();
        jLabelDescriereFisier = new javax.swing.JLabel();
        jTextFieldNumeFisier = new javax.swing.JTextField();
        jTextFieldTipFisier = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDescAdaugaFisiere = new javax.swing.JTextArea();
        jFileChooserProvenientaFisiere = new javax.swing.JFileChooser();
        jBtnSalvareFisier = new javax.swing.JButton();
        jLabelAvertizareAdaugareFisiere = new javax.swing.JLabel();
        jFileChooserDestinatieFisiere = new javax.swing.JFileChooser();
        jPanelStergereFisiere = new javax.swing.JPanel();
        jLabelTitluStergereFisiere = new javax.swing.JLabel();
        jFileChooserStergereFisiere = new javax.swing.JFileChooser();
        jBtnStergeFisier = new javax.swing.JButton();
        jLabelAvertismenteStergereFisiere = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 680));

        jTabbedPaneAdmFisiere.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jTabbedPaneAdmFisiere.setMinimumSize(new java.awt.Dimension(1080, 680));
        jTabbedPaneAdmFisiere.setPreferredSize(new java.awt.Dimension(1080, 680));

        jPanelMeniuFisiere.setMinimumSize(new java.awt.Dimension(1080, 680));
        jPanelMeniuFisiere.setPreferredSize(new java.awt.Dimension(1080, 680));

        jLabelTitluAdmFisiere.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabelTitluAdmFisiere.setText("Administrare fisiere");

        jTableFisiere.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jTableFisiere.setForeground(new java.awt.Color(0, 153, 255));
        jTableFisiere.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nume", "Tip", "Descriere", "Locatie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFisiere);

        jBtnVizFisiere.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jBtnVizFisiere.setText("Vizualizare fisiere");
        jBtnVizFisiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVizFisiereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMeniuFisiereLayout = new javax.swing.GroupLayout(jPanelMeniuFisiere);
        jPanelMeniuFisiere.setLayout(jPanelMeniuFisiereLayout);
        jPanelMeniuFisiereLayout.setHorizontalGroup(
            jPanelMeniuFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMeniuFisiereLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMeniuFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelMeniuFisiereLayout.createSequentialGroup()
                        .addComponent(jLabelTitluAdmFisiere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnVizFisiere)
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMeniuFisiereLayout.setVerticalGroup(
            jPanelMeniuFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMeniuFisiereLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMeniuFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitluAdmFisiere)
                    .addComponent(jBtnVizFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmFisiere.addTab("Administrare fisiere", jPanelMeniuFisiere);

        jPanelAdaugaFisiere.setMinimumSize(new java.awt.Dimension(1080, 680));
        jPanelAdaugaFisiere.setPreferredSize(new java.awt.Dimension(1080, 680));

        jLabelTitluAdaugareFisiere.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabelTitluAdaugareFisiere.setText("Adaugare fisiere");

        jLabelNumeFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelNumeFisier.setText("Nume fisier:");

        jLabelTipFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelTipFisier.setText("Tip fisier:");

        jLabelDescriereFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelDescriereFisier.setText("Descriere:");

        jTextFieldNumeFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jTextFieldNumeFisier.setForeground(new java.awt.Color(0, 153, 255));

        jTextFieldTipFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jTextFieldTipFisier.setForeground(new java.awt.Color(0, 153, 255));

        jTextAreaDescAdaugaFisiere.setColumns(20);
        jTextAreaDescAdaugaFisiere.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jTextAreaDescAdaugaFisiere.setForeground(new java.awt.Color(0, 153, 255));
        jTextAreaDescAdaugaFisiere.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDescAdaugaFisiere);

        jBtnSalvareFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jBtnSalvareFisier.setText("Salveaza");
        jBtnSalvareFisier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvareFisierActionPerformed(evt);
            }
        });

        jLabelAvertizareAdaugareFisiere.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelAvertizareAdaugareFisiere.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelAdaugaFisiereLayout = new javax.swing.GroupLayout(jPanelAdaugaFisiere);
        jPanelAdaugaFisiere.setLayout(jPanelAdaugaFisiereLayout);
        jPanelAdaugaFisiereLayout.setHorizontalGroup(
            jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                        .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNumeFisier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTipFisier)
                                    .addComponent(jLabelDescriereFisier)))
                            .addComponent(jLabelAvertizareAdaugareFisiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumeFisier)
                            .addComponent(jTextFieldTipFisier)))
                    .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                        .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitluAdaugareFisiere)
                            .addComponent(jBtnSalvareFisier, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFileChooserProvenientaFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileChooserDestinatieFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAdaugaFisiereLayout.setVerticalGroup(
            jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                        .addComponent(jLabelTitluAdaugareFisiere)
                        .addGap(36, 36, 36)
                        .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeFisier)
                            .addComponent(jTextFieldNumeFisier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipFisier)
                            .addComponent(jTextFieldTipFisier))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAdaugaFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                                .addComponent(jLabelDescriereFisier)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelAvertizareAdaugareFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSalvareFisier, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelAdaugaFisiereLayout.createSequentialGroup()
                        .addComponent(jFileChooserProvenientaFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFileChooserDestinatieFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPaneAdmFisiere.addTab("Adaugare fisiere", jPanelAdaugaFisiere);

        jPanelStergereFisiere.setMinimumSize(new java.awt.Dimension(1080, 680));
        jPanelStergereFisiere.setPreferredSize(new java.awt.Dimension(1080, 680));

        jLabelTitluStergereFisiere.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabelTitluStergereFisiere.setText("Stergere fisiere");

        jBtnStergeFisier.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jBtnStergeFisier.setText("Stergere");
        jBtnStergeFisier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStergeFisierActionPerformed(evt);
            }
        });

        jLabelAvertismenteStergereFisiere.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelAvertismenteStergereFisiere.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelStergereFisiereLayout = new javax.swing.GroupLayout(jPanelStergereFisiere);
        jPanelStergereFisiere.setLayout(jPanelStergereFisiereLayout);
        jPanelStergereFisiereLayout.setHorizontalGroup(
            jPanelStergereFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStergereFisiereLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStergereFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStergereFisiereLayout.createSequentialGroup()
                        .addComponent(jLabelTitluStergereFisiere)
                        .addGap(66, 66, 66))
                    .addGroup(jPanelStergereFisiereLayout.createSequentialGroup()
                        .addComponent(jFileChooserStergereFisiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabelAvertismenteStergereFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelStergereFisiereLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jBtnStergeFisier, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStergereFisiereLayout.setVerticalGroup(
            jPanelStergereFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStergereFisiereLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitluStergereFisiere)
                .addGap(18, 18, 18)
                .addGroup(jPanelStergereFisiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFileChooserStergereFisiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAvertismenteStergereFisiere, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jBtnStergeFisier, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPaneAdmFisiere.addTab("Stergere fisiere", jPanelStergereFisiere);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAdmFisiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAdmFisiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }//GEN-END:initComponents

    private void jBtnVizFisiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVizFisiereActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableFisiere.getModel();
        fisiereSingle.clear();
        model.setRowCount(0);
        try {
            fisiereSingle = fisierSingleManagement.getAll();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        for (FisierSingle f : fisiereSingle) {
            model.addRow(new Object[]{f.getNume(), f.getTip(), f.getDescriere(), f.getLocatie()});
        }
    }//GEN-LAST:event_jBtnVizFisiereActionPerformed

    private void jBtnSalvareFisierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvareFisierActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTextFieldNumeFisier.getText().isEmpty() && !jTextFieldTipFisier.getText().isEmpty() &&
                !jTextAreaDescAdaugaFisiere.getText().isEmpty() && jFileChooserProvenientaFisiere.getSelectedFile().exists()) {
                try {
                    Files.copy(Paths.get(jFileChooserProvenientaFisiere.getSelectedFile().getAbsolutePath().toString()),
                               Paths.get(jFileChooserDestinatieFisiere.getCurrentDirectory().getAbsolutePath().toString() +
                                         "\\" + jFileChooserProvenientaFisiere.getSelectedFile().getName().toString()),
                                         StandardCopyOption.REPLACE_EXISTING);
                    fisierSingleManagement.save(new FisierSingle(jFileChooserProvenientaFisiere.getSelectedFile().getName(),
                                                                 jTextFieldTipFisier.getText(),
                                                                 jTextAreaDescAdaugaFisiere.getText(),
                                                                 jFileChooserDestinatieFisiere.getCurrentDirectory().getAbsolutePath() + "\\" +
                                                                 jFileChooserProvenientaFisiere.getSelectedFile().getName().toString()));
                    Path destinatieFisier = Paths.get(jFileChooserDestinatieFisiere.getCurrentDirectory().getAbsolutePath() +
                                                      jFileChooserProvenientaFisiere.getSelectedFile().getName().toString());
                    assert(destinatieFisier.toFile().exists());
                    assert(Files.readAllLines(jFileChooserProvenientaFisiere.getSelectedFile().toPath().getFileName().getRoot())
                                              .equals(Files.readAllLines(destinatieFisier)));
                    jFileChooserDestinatieFisiere.rescanCurrentDirectory();
                    } catch(FileAlreadyExistsException ex) {
                        jLabelAvertizareAdaugareFisiere.setText("<html><center>Acest fisier<br> exista deja!</center><html/>");
                    } catch (IOException ex) {
                        java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    if (jFileChooserProvenientaFisiere.getSelectedFile() != null) {
                        jLabelAvertizareAdaugareFisiere.setText("<html><center>Fisierul a<br> fost salvat!</center><html/>");
                    }
                } else {
                    jLabelAvertizareAdaugareFisiere.setText("<html><center>Toate campurile<br> trebuiesc completate!</center><html/>");
                }
            } catch(NullPointerException ex) {
                jLabelAvertizareAdaugareFisiere.setText("<html><center>Trebuie sa alegi<br> un fisier!</center><html/>");
            }
    }//GEN-LAST:event_jBtnSalvareFisierActionPerformed

    private void jBtnStergeFisierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStergeFisierActionPerformed
        // TODO add your handling code here:
        if(jFileChooserStergereFisiere.getSelectedFile().isFile()) {
            try {
                fisierSingleManagement.deleteByPath(jFileChooserStergereFisiere.getSelectedFile().getAbsolutePath().toString());
                boolean success = Files.deleteIfExists(Paths.get(jFileChooserStergereFisiere.getSelectedFile()
                                                                                            .getAbsolutePath()
                                                                                            .toString()));
                assert(success);
                jLabelAvertismenteStergereFisiere.setText("<html><center>Fisierul selectat a fost sters!</center><html/>");
                jFileChooserStergereFisiere.rescanCurrentDirectory();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch(NullPointerException ex) {
                jLabelAvertismenteStergereFisiere.setText("<html><center>Trebuie sa alegi fie un fisier sau o mapa!</center></html>");
            }
        } else if(jFileChooserStergereFisiere.getSelectedFile().isDirectory()) {
            Object[] selectie = {"Confirma", "Anuleaza"};
            UIManager.put("OptionPane.messageForeground", Color.RED);
            UIManager.put("OptionPane.messageFont", new Font("DialogInput", Font.BOLD, 18));
            UIManager.put("OptionPane.buttonFont", new Font("DialogInput", Font.BOLD, 18));
            int optiune = JOptionPane.showOptionDialog(DLMAppStart.appStart,
                "<html><center>Esti pe cale de a sterge o mapa, ce contine mai multe fisiere<br>" +
                "pe care s-ar putea sa nu le mai poti recupera inapoi!<br>" +
                "Esti absolut sigur ca doresti sa continui?</center></html>",
                "Confirmare:",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,     //do not use a custom Icon
                selectie,  //the titles of buttons
                selectie[0]); //default button title
            if(optiune == JOptionPane.YES_OPTION) {
                try {
                    File[] arrayFisiere = jFileChooserStergereFisiere.getSelectedFile().listFiles();
                    for(File f : arrayFisiere){
                        boolean success = Files.deleteIfExists(Paths.get(f.toURI()));
                        assert(success);
                        fisierSingleManagement.deleteByPath(f.getAbsolutePath());
                    }
                    boolean success = Files.deleteIfExists(Paths.get(jFileChooserStergereFisiere.getSelectedFile()
                                                                                                .getAbsolutePath()
                                                                                                .toString()));
                    assert(success);
                    jLabelAvertismenteStergereFisiere.setText("<html><center>Mapa selectata a fost stersa!</center><html/>");
                    jFileChooserStergereFisiere.rescanCurrentDirectory();
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(MeniuTaburi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch(NullPointerException ex) {
                    jLabelAvertismenteStergereFisiere.setText("<html><center>Trebuie sa alegi fie un fisier sau o mapa!</center></html>");
                }
            }  
        }
    }//GEN-LAST:event_jBtnStergeFisierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalvareFisier;
    private javax.swing.JButton jBtnStergeFisier;
    private javax.swing.JButton jBtnVizFisiere;
    private javax.swing.JFileChooser jFileChooserDestinatieFisiere;
    private javax.swing.JFileChooser jFileChooserProvenientaFisiere;
    private javax.swing.JFileChooser jFileChooserStergereFisiere;
    private javax.swing.JLabel jLabelAvertismenteStergereFisiere;
    private javax.swing.JLabel jLabelAvertizareAdaugareFisiere;
    private javax.swing.JLabel jLabelDescriereFisier;
    private javax.swing.JLabel jLabelNumeFisier;
    private javax.swing.JLabel jLabelTipFisier;
    private javax.swing.JLabel jLabelTitluAdaugareFisiere;
    private javax.swing.JLabel jLabelTitluAdmFisiere;
    private javax.swing.JLabel jLabelTitluStergereFisiere;
    private javax.swing.JPanel jPanelAdaugaFisiere;
    private javax.swing.JPanel jPanelMeniuFisiere;
    private javax.swing.JPanel jPanelStergereFisiere;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneAdmFisiere;
    private javax.swing.JTable jTableFisiere;
    private javax.swing.JTextArea jTextAreaDescAdaugaFisiere;
    private javax.swing.JTextField jTextFieldNumeFisier;
    private javax.swing.JTextField jTextFieldTipFisier;
    // End of variables declaration//GEN-END:variables

    private void selectoareMapeSiFisiere() {
        jFileChooserProvenientaFisiere.setControlButtonsAreShown(false); 
        jFileChooserProvenientaFisiere.setCurrentDirectory(javax.swing.filechooser.FileSystemView.getFileSystemView().getHomeDirectory());
        jFileChooserDestinatieFisiere.setControlButtonsAreShown(false);
        jFileChooserDestinatieFisiere.setCurrentDirectory(new File(fisiereApp));
        jFileChooserStergereFisiere.setCurrentDirectory(new File(fisiereApp));
        jFileChooserStergereFisiere.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooserStergereFisiere.setControlButtonsAreShown(false);
    }
}