package Components.Events.project;
import DataBaseConn.project.DataBaseConn;
import Digitalizare.Laborator.Metrologie.project.DLMAppStart;
import Users.project.UsersDAO;
import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Dragos
 */
public class MeniuLogare extends javax.swing.JPanel {  
    String connectionUrl = String.format("jdbc:mysql://%s:%s/%s", "127.0.0.1", "3306", "dsr");
    DataBaseConn db = new DataBaseConn(connectionUrl, "root", "@Root123#");
    Connection conn = db.getConnection();
    //public String loggedUser;

    /** Creates new form MeniuLogare */
    public MeniuLogare() {
        try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLMAppStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.updateUI();
        ImageIcon logoImage = new ImageIcon(
                              new ImageIcon("C:\\Oracle\\Middleware\\Oracle_Home\\jdeveloper\\" +
                                            "mywork\\mywork\\DigitalizareLaboratorMetrologie\\" +
                                            "project\\FisiereDLM\\FisiereAplicatie\\Dsr.png")
                              .getImage().getScaledInstance(848, 854, Image.SCALE_SMOOTH));
        jLabelLogoLogare.setIcon(logoImage);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabelTitlu = new javax.swing.JLabel();
        jLabelLogareUti = new javax.swing.JLabel();
        jTextNumeUti = new javax.swing.JTextField();
        jParolaUti = new javax.swing.JPasswordField();
        jLabelUtilizator = new javax.swing.JLabel();
        jLabelParola = new javax.swing.JLabel();
        jAfisareParola = new javax.swing.JCheckBox();
        jBtnLogare = new javax.swing.JButton();
        jLabelAvertismente = new javax.swing.JLabel();
        jLabelLogoLogare = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1320, 960));

        jLabelTitlu.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabelTitlu.setText("Sistem Informatic Laborator Metrologie");

        jLabelLogareUti.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelLogareUti.setText("Logare utilizator");

        jTextNumeUti.setFont(new java.awt.Font("DialogInput", 1, 32)); // NOI18N

        jParolaUti.setFont(new java.awt.Font("DialogInput", 1, 32)); // NOI18N

        jLabelUtilizator.setFont(new java.awt.Font("DialogInput", 1, 32)); // NOI18N
        jLabelUtilizator.setText("Nume utilizator:");

        jLabelParola.setFont(new java.awt.Font("DialogInput", 1, 32)); // NOI18N
        jLabelParola.setText("Parola utilizator:");

        jAfisareParola.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jAfisareParola.setText("Afiseaza parola");
        jAfisareParola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAfisareParolaActionPerformed(evt);
            }
        });

        jBtnLogare.setFont(new java.awt.Font("DialogInput", 1, 32)); // NOI18N
        jBtnLogare.setText("Logare");
        jBtnLogare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogareActionPerformed(evt);
            }
        });

        jLabelAvertismente.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelAvertismente.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitlu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jParolaUti, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNumeUti)
                            .addComponent(jLabelAvertismente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUtilizator)
                                    .addComponent(jLabelLogareUti)
                                    .addComponent(jLabelParola)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jAfisareParola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBtnLogare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 62, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogoLogare, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTitlu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabelLogareUti)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelUtilizator, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNumeUti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabelParola, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jParolaUti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jAfisareParola)
                        .addGap(52, 52, 52)
                        .addComponent(jBtnLogare, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAvertismente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogoLogare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }//GEN-END:initComponents

    private void jBtnLogareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogareActionPerformed
        // TODO add your handling code here:
        String text = jTextNumeUti.getText();
        String parola = jParolaUti.getText();
        Map<String, String> utilizatori = new HashMap<>();
        UsersDAO userManagement = new UsersDAO(conn);
        try {
            utilizatori = userManagement.getAll();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MeniuLogare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        if (utilizatori.containsKey(text)) {
            if (utilizatori.get(text).equals(parola)) {
                DLMAppStart.appStart.remove(DLMAppStart.logare);
                MeniuTaburi meniu = new MeniuTaburi();
                DLMAppStart.appStart.add(meniu);
                DLMAppStart.appStart.revalidate();
                DLMAppStart.appStart.repaint(); 
            } else {
                jLabelAvertismente.setText("<html><center>Parola incorecta! Incercati din nou!</center><html/>");
            }
        } else {
            jLabelAvertismente.setText("<html><center>Nume de utilizator incorect!<br> Incercati din nou!</center><html/>");
        }
    }//GEN-LAST:event_jBtnLogareActionPerformed

    private void jAfisareParolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAfisareParolaActionPerformed
        // TODO add your handling code here:
        if (jParolaUti.echoCharIsSet()) {
            jParolaUti.setEchoChar((char) 0);
        } else {
            jParolaUti.setEchoChar('•');
        }
    }//GEN-LAST:event_jAfisareParolaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jAfisareParola;
    private javax.swing.JButton jBtnLogare;
    private javax.swing.JLabel jLabelAvertismente;
    private javax.swing.JLabel jLabelLogareUti;
    private javax.swing.JLabel jLabelLogoLogare;
    private javax.swing.JLabel jLabelParola;
    private javax.swing.JLabel jLabelTitlu;
    private javax.swing.JLabel jLabelUtilizator;
    private javax.swing.JPasswordField jParolaUti;
    private javax.swing.JTextField jTextNumeUti;
    // End of variables declaration//GEN-END:variables

}